#region Copyright

//+ Nalarium Pro 3.0 - Web Module
//+ Copyright © Jampad Technology, Inc. 2008-2010

#endregion

using System;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Configuration;
using System.Web.UI;

namespace Nalarium.Web
{
    public static class MachineKeyCryptographer
    {
        //- @EncryptCode -//
        public static String EncryptCode(String code)
        {
            if (String.IsNullOrEmpty(code))
            {
                return String.Empty;
            }
            Type pageType = typeof(Page);
            MethodInfo methodInfo = pageType.GetMethod("EncryptString", BindingFlags.Static | BindingFlags.NonPublic);
            //+
            return methodInfo.Invoke(null, new Object[]
                                           {
                                               code
                                           }) as string;
        }

        //- @DecryptCode -//
        public static String DecryptCode(String code)
        {
            if (String.IsNullOrEmpty(code))
            {
                return String.Empty;
            }
            Byte[] encryptedData = HttpServerUtility.UrlTokenDecode(code);
            Type machineKeySection = typeof(MachineKeySection);
            var paramTypes = new[]
                             {
                                 typeof(Boolean), typeof(Byte[]), typeof(Byte[]), typeof(Int32), typeof(Int32)
                             };
            MethodInfo encryptOrDecryptData = machineKeySection.GetMethod("EncryptOrDecryptData", BindingFlags.Static | BindingFlags.NonPublic, null, paramTypes, null);
            try
            {
                var decryptedData = (Byte[])encryptOrDecryptData.Invoke(null, new Object[]
                                                                              {
                                                                                  false, encryptedData, null, 0, encryptedData.Length
                                                                              });
                string decrypted = Encoding.UTF8.GetString(decryptedData);
                //+
                return decrypted;
            }
            catch (TargetInvocationException)
            {
                return string.Empty;
            }
        }

        //- @DecryptCodeAsStringArray -//
        /// <summary>
        /// Decrypts an encrypted ASP.NET resource URL as a string array containing both the resource type and assembly.  It is specific to resources generated by the current machine.
        /// </summary>
        /// <param name="code">Encrypted base64 resource URL.  String.Empty is there is an error.</param>
        /// <returns>Decrypted string array representing both the resource type and assembly.</returns>
        public static String[] DecryptCodeAsStringArray(String code)
        {
            String data = DecryptCode(code);
            if (String.IsNullOrEmpty(data))
            {
                return null;
            }
            String[] partArray = data.Split('|');
            if (partArray.Length != 2)
            {
                return null;
            }
            //+
            return new[]
                   {
                       partArray[0][0].ToString(), partArray[0].Substring(1, partArray[0].Length - 1), partArray[1]
                   };
        }
    }
}